### ISSUE TITLE
Carrot.

### ISSUE THREAD

**Issue by BlockIX** [lightbulblighter/Rboxlo2#1]
Srsly? After putting a rat in the last project you think we will fall for this?

Write a reason why this is not a rat:

**Comment by lightbulblighter** [comment]
Hi

**Comment by BlockIX** [comment]
> Hi

Hello, how much money exactly are you going to steal from little kids mom's credit card's to buy v-bucks?

**Comment by lightbulblighter** [comment]
This isn't Rboxlo this is Rboxlo2

**Comment by Mantaraix** [comment]
This is madness.
