### ISSUE TITLE
Where is fuck is the website?

### ISSUE THREAD

**Issue by BlockIX** [lightbulblighter/Rboxlo2#4]
The fuck? The only index.js empty file be like

**Comment by Mantaraix** [comment]
Retard

**Comment by lightbulblighter** [comment]
DAS FAX BRO ONG

**Comment by BlockIX** [comment]
OMG!!!?!?!?!?!?1/!?!?!?!/!/!?!/!1?

gosh wait until mommy give you your next allowence. Stop ratting kids for their moms credit/debit cards faggot.

**Comment by lightbulblighter** [comment]
Where is fuck is the website?

**Comment by Mantaraix** [comment]
Mic up on github rn i will shatter your cranium Derek Stevenson
