### ISSUE TITLE
How to compile Rboxlo2 easy tutorial no virus!

### ISSUE THREAD

**Issue by BlockIX** [lightbulblighter/Rboxlo2#5]
1. Make sure your moms credit card information is stored on your computer (very important)
2. Download this thingy called "Visual Studio" you need it to make this game work.
3. Make sure your home alone because you don't want any of your parents inside your house during this
4. Open the client, and the .sln file inside in visual studio, and press the **build** button.
5. Now in about 15 minutes an rboxlo cd-rom game card for your game cube is going to show up at your door
6. ignore any calls from your mom (its just scammers diguesed as your mom telling that someone spend 10000000$ on his/her credit card)
7. Enjoy rboxlo!

**Comment by Mantaraix** [comment]
Talk ya shit king let ya nuts hang derek stevenson

**Comment by lightbulblighter** [comment]
Dis what happens when u leave the sped kid unattended for too long

**Comment by Mantaraix** [comment]
Hes like a shopping trolley u cannot leave that trolleuy out of sight
