### ISSUE TITLE
How to potty train the kids you rat (You cant just leave them there all alone)

### ISSUE THREAD

**Issue by BlockIX** [lightbulblighter/Rboxlo2#6]
When Are Ratted Kids Ready to Toilet Train?
Many parents are unsure about when to start toilet training or "potty training." Not all kids are ready at the same age, so it's important to watch your child for signs of readiness, such as stopping an activity for a few seconds or clutching his or her diaper.

Instead of using age, look for signs that your child may be ready to start heading for the potty, such as being able to:

follow simple instructions
understand and use words about using the potty
make the connection between the urge to pee or poop and using the potty
keep a diaper dry for 2 hours or more
get to the potty, sit on it for enough time, and then get off the potty
pull down diapers, disposable training pants, or underpants
show an interest in using the potty or wearing underpants
Most children begin to show these signs when they're between 18 and 24 months old, though some may not be ready until later than that. And boys often start later and take longer to learn to use the potty than girls.

There are some times when you may want to put off starting toilet training, such as:

when traveling
around the birth of a sibling
changing from the crib to the bed
moving to a new house
when your child is sick (especially if diarrhea is a factor)

**Comment by lightbulblighter** [comment]
What the fuck

**Comment by Mantaraix** [comment]
Do you speak to your mother with that mouth Derek
